package auth

const (
	ErrUserExists       = "THE SPECIFIED EMAIL ADDRESS IS ALREADY IN USE"
	ErrNonExistentEmail = "THE SPECIFIED EMAIL ADDRESS IS UNREGISTERED"
	ErrWrongPassword    = "THE SPECIFIED PASSWORD IS INCORRECT"
	ErrJWT              = "COULDN'T CREATE A TOKEN"
)
